kind: pipeline
type: kubernetes
name: terraform-provider-mikrotik

metadata:
  namespace: default

# Allows the pods to resolve domain names outside the k8s cluster
dns_config:
  options:
    - name: ndots
      value: 1

steps:
  - name: build
    image: golang:1.15
    commands:
      - make build
  - name: unit test
    image: golang:1.15
    environment:
      MIKROTIK_HOST:
        from_secret: MIKROTIK_HOST
      MIKROTIK_USER:
        from_secret: MIKROTIK_USER
      MIKROTIK_PASSWORD:
        from_secret: MIKROTIK_PASSWORD
    commands:
      - make testacc