kind: pipeline
type: kubernetes
name: terraform-provider-mikrotik

metadata:
  namespace: default

# Allows the pods to resolve domain names outside the k8s cluster
dns_config:
  options:
    - name: ndots
      value: 1

steps:
  - name: build
    image: golang:1.15.11
    commands:
      - make build
  - name: unit test
    image: golan:1.15.11
    commands:
      - make testacc